export const boardTemplate = [
  {
    activities: "[]",
    createdAt: "",
    id: 1,
    info: '{"backgroundImage":"","author":"1","type":"personalBoard"}',
    labels: "[]",
    lists: "[]",
    members: "[]",
    name: "Technology",
    updatedAt: "",
  },
  {
    activities: "[]",
    createdAt: "",
    id: 2,
    info: '{"backgroundImage":"","author":"1","type":"personalBoard"}',
    labels: "[]",
    lists: "[]",
    members: "[]",
    name: "Business",
    updatedAt: "",
  },
  {
    activities: "[]",
    createdAt: "",
    id: 3,
    info: '{"backgroundImage":"","author":"1","type":"personalBoard"}',
    labels: "[]",
    lists: "[]",
    members: "[]",
    name: "Design",
    updatedAt: "",
  },
  {
    activities: "[]",
    createdAt: "",
    id: 4,
    info: '{"backgroundImage":"","author":"1","type":"personalBoard"}',
    labels: "[]",
    lists: "[]",
    members: "[]",
    name: "Marketing",
    updatedAt: "",
  },
  {
    activities: "[]",
    createdAt: "",
    id: 5,
    info: '{"backgroundImage":"","author":"1","type":"personalBoard"}',
    labels: "[]",
    lists: "[]",
    members: "[]",
    name: "Project Management",
    updatedAt: "",
  },
];
